---
info:
  title: Grimoirelab Perceval
  description: Send Sir Perceval on a quest to retrieve and gather data from software
    repositories.
  x-cortex-git:
    github:
      alias: r7org
      repository: rapid7/grimoirelab-perceval
  x-cortex-tag: grimoirelab-perceval
  x-cortex-type: service
  x-cortex-domain-parents:
  - tag: metasploit
openapi: 3.0.1
servers:
- url: "/"
